// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Script } from "forge-std/Script.sol";
import { DevOpsTools } from "foundry-devops/src/DevOpsTools.sol";

contract ClaimAirdrop is Script {

    function run() external {
        address mostRecentlyDeployed = DevOpsTools.get_most_recent_deployment("MerkleAirdrop", block.chainid);
        claimAirdrop(mostRecentlyDeployed);
    }

	function claimAirdrop(address airdropContractAddress) public {
        // Define parameters for the claim function
        address CLAIMING_ADDRESS = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266; // Example address
        uint256 CLAIMING_AMOUNT = 25 * 1e18; // Example: 25 tokens with 18 decimals

        // Merkle Proof for CLAIMING_ADDRESS and CLAIMING_AMOUNT
        // These values are copied from the output.json generated by MakeMerkle.s.sol
        // for the specific CLAIMING_ADDRESS (0xf39...)
        bytes32 PROOF_ONE = 0xd1445c931158119d0449ffcac3c947d028c359c34a664d95962b3b55c6ad; // Example proof element
        bytes32 PROOF_TWO = 0xe5ebd1e1b5a5478a944eca36a9a954ac3b68216875f6524caa71d87896576; // Example proof element
        bytes32[] memory proof = new bytes32[](2); // Assuming a proof length of 2 for this example
        proof[0] = PROOF_ONE;
        proof[1] = PROOF_TWO;

        // v, r, s signature components are still needed
		// vm.sign(privateKey, digest)
		// cast wallet sign <MESSAGE_TO_SIGN> --private-key <PRIVATE_KEY>
		
        vm.startBroadcast();
        // MerkleAirdrop(airdropContractAddress).claim(CLAIMING_ADDRESS, CLAIMING_AMOUNT, proof, v, r, s);
        vm.stopBroadcast();

    }
}
