// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { Script } from "forge-std/Script.sol";
import { DevOpsTools } from "foundry-devops/src/DevOpsTools.sol";
import { MerkleAirdrop } from "../src/MerkleAirdrop.sol";

contract ClaimAirdrop is Script {
    // address constant MERKLE_AIRDROP_CONTRACT = 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512;
    address constant CLAIMING_ADDRESS = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266;
    uint256 constant CLAIMING_AMOUNT = 25 * 1e18;

	bytes private SIGNATURE = hex"12e145324b60cd4d302bfad59f72946d45ffad8b9fd608e672fd7f02029de7c438cfa0b8251ea803f361522da811406d441df04ee99c3dc7d65f8550e12be2ca1c";

	bytes32[] proof;

	error __MyScriptName_InvalidSignatureLength(); // Use a script-specific name


    function run() external {

        address mostRecentlyDeployed = DevOpsTools.get_most_recent_deployment("MerkleAirdrop", block.chainid);
		MerkleAirdrop merkleAirdrop = MerkleAirdrop(mostRecentlyDeployed);

        vm.startBroadcast();
		(uint8 v, bytes32 r, bytes32 s) = splitSignature(SIGNATURE);

        merkleAirdrop.claim(
            CLAIMING_ADDRESS,
            CLAIMING_AMOUNT,
            proof,
            v,
            r,
            s
        );

        vm.stopBroadcast();

    }

	// function claimAirdrop(address airdropContractAddress) public {
    //     // Define parameters for the claim function
    //     address CLAIMING_ADDRESS = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266; // Example address
    //     uint256 CLAIMING_AMOUNT = 25 * 1e18; // Example: 25 tokens with 18 decimals

    //     // Merkle Proof for CLAIMING_ADDRESS and CLAIMING_AMOUNT
    //     // These values are copied from the output.json generated by MakeMerkle.s.sol
    //     // for the specific CLAIMING_ADDRESS (0xf39...)
    //     bytes32 PROOF_ONE = 0xd1445c931158119d0449ffcac3c947d028c359c34a664d95962b3b55c6ad; // Example proof element
    //     bytes32 PROOF_TWO = 0xe5ebd1e1b5a5478a944eca36a9a954ac3b68216875f6524caa71d87896576; // Example proof element
    //     bytes32[] memory proof = new bytes32[](2); // Assuming a proof length of 2 for this example
    //     proof[0] = PROOF_ONE;
    //     proof[1] = PROOF_TWO;

    //     // v, r, s signature components are still needed
	// 	// vm.sign(privateKey, digest)
	// 	// cast wallet sign <MESSAGE_TO_SIGN> --private-key <PRIVATE_KEY>
		
    //     vm.startBroadcast();
    //     // MerkleAirdrop(airdropContractAddress).claim(CLAIMING_ADDRESS, CLAIMING_AMOUNT, proof, v, r, s);
    //     vm.stopBroadcast();

    // }


	/**
	 * @notice Splits a 65-byte concatenated signature (r, s, v) into its components.
	 * @param sig The concatenated signature as bytes.
	 * @return v The recovery identifier (1 byte).
	 * @return r The r value of the signature (32 bytes).
	 * @return s The s value of the signature (32 bytes).
	 */
	function splitSignature(bytes memory sig)
		public
		pure
		returns (uint8 v, bytes32 r, bytes32 s)
	{
		// Standard ECDSA signatures are 65 bytes:
		// r (32) + s (32) + v (1)
		if (sig.length != 65) {
			revert __MyScriptName_InvalidSignatureLength();
		}

		assembly {
			// r = first 32 bytes
			r := mload(add(sig, 0x20))

			// s = next 32 bytes
			s := mload(add(sig, 0x40))

			// v = first byte of next 32 bytes
			v := byte(0, mload(add(sig, 0x60)))
			
			// EIP-155: With EIP-155 (transaction replay protection on different chains), v values became chain-specific: chain_id * 2 + 35 or chain_id * 2 + 36.
			// if (v < 27) v += 27;
		}
	}
}
